### ISSUE TITLE
Possible inaccuracy with move_abs on Win10

### ISSUE THREAD

**Issue by Zennii** [obv-mikhail/InputBot#16]
Platform: Windows 10
If my screen dimensions are relevant: 2560x1440
I have three monitors, these tests were done on my farthest left one, which is the one with the taskbar, which is on the left side of the screen.

I'm trying to move the mouse, and I assumed `MouseCursor.move_abs()` was ideal because I have absolute coordinates from the winapi. In the simplest form, I tried to do the following:

```rust
    let left = 486;
    let top = 347;
    MouseCursor.move_abs(left, top);
```

Which is inaccurate by 285x2 pixels. At (1044, 350) it's off by 558x3 which seems like it scales or something. (0,0) works, and I can move the cursor to the correct screen coordinate by doing a `move_abs` to (0,0) and then a `move_rel` to my coordinates like the following:

```rust
    let left = 486;
    let top = 347;
    MouseCursor.move_abs(0, 0);
    MouseCursor.move_rel(left, top);
```
I can work with this, although it seems unexpected.

Is this a bug or am I missing a detail on `move_abs`?

**Comment by obv-mikhail** [comment]
@Zennii this is a bug. I guess I am doing something wrong in here - https://github.com/obv-mikhail/InputBot/blob/master/src/windows/mod.rs#L72.

I think Enigo is probably doing this correctly - https://github.com/enigo-rs/enigo/blob/master/src/win/win_impl.rs#L53. Although, I am not sure how exactly this works..

**Comment by Zennii** [comment]
@obv-mikhail Well one important thing I've noticed while looking around, is if you see here:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics#SM_CXVIRTUALSCREEN

It states "The virtual screen is the bounding rectangle of all display monitors."

Whereas since you don't have the `MOUSEEVENTF_VIRTUALDESK` flag:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput#MOUSEEVENTF_VIRTUALDESK

You are not mapping to "all display monitors", just the primary one. This might result in your coordinates being incorrect relative to the amount of monitors.

I might be wrong, but in my findings it seems like you subtract by SM_XVIRTUALSCREEN and SM_YVIRTUALSCREEN (The top left of the virtual screen) to cover the case that there is monitors to the top/left of the primary monitor (As then it would produce values other than just 0). It sounds like a very strange way for windows to go about this. Though that is only my base understanding from quickly looking around the internet.

**Comment by benediktwerner** [comment]
Is there a reason why you are not using [SetCursorPos](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcursorpos)?

I have found that both Enigo and inputbot are completely inaccurate when trying to set the absolute mouse position on my dual monitor setup with standard scaling and 1920x1080 resolution (although I'm not sure if the dual monitors even has anything to do with it). IIRC even the relative movement methods don't work correctly and sometimes skip pixels when trying to move only a single pixel.

Using the winapi directly with SetCursorPos and GetCursorPos works correctly. It would also be quite easy to add a method to get the mouse position with GetCursorPos which would be quite useful IMO. Although somebody would have to add an equivalent method for Linux.

**Comment by obv-mikhail** [comment]
@benediktwerner this is good to know, thanks! I am not sure how SetCursorPos works, do you know if it works in fullscreen DirectX games for example?

If you would be interested in adding the methods, the addition would be appreciated. I think the Linux equivalent could be left unimplemented for now.

**Comment by benediktwerner** [comment]
@obv-mikhail I just tested it in Desperados III (Unity engine) and Valorant (Unreal Engine) and it seems to work fine.

I'll create a PR in the next few days.

**Comment by obv-mikhail** [comment]
0.5.0 now released with the changes @benediktwerner implemented to make this work properly.
