### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by emhagman** [obv-mikhail/InputBot#18]
It appears that there is no LICENSE on the project. By default, this means we have no permission to use, modify, etc. Do you mind picking a license?

You can read more here: https://choosealicense.com/no-permission/
And to help pick one: https://choosealicense.com/

**Comment by obv-mikhail** [comment]
@emhagman I specified "MIT" as the license in Cargo.toml. I guess there should be a license file in the repository though - I would be happy to add it.

**Comment by emhagman** [comment]
Thanks! Sorry I didn't see that. I don't know enough about licensing to know if it's enough to have it in the `Cargo.toml` or if you always need the file `LICENSE` file as well

**Comment by obv-mikhail** [comment]
Added an MIT license file - https://github.com/obv-mikhail/InputBot/blob/develop/LICENSE-MIT.
