### ISSUE TITLE
Build failed on latest rustc (darwin)

### ISSUE THREAD

**Issue by Enity** [obv-mikhail/InputBot#26]
![image](https://user-images.githubusercontent.com/2884517/98801551-0027dd80-2423-11eb-9379-3ea13bb743f6.png)

**Comment by obv-mikhail** [comment]
Macs are not supported at the moment, but contributions adding support for them are welcome.

**Comment by Enity** [comment]
Ok thank you. In fact, I need an app for windows, but I wrote it under macos

**Comment by aaronleopold** [comment]
Hey there, this is a really cool library! I think I might try and take a stab at adding macos support in my spare time over the next few months if that's alright by you 😄

I can create an issue for it, as well, if you'd like

**Comment by obv-mikhail** [comment]
@aaronleopold go for it! Up to you if you want to create a tracking issue.
