### ISSUE TITLE
How do I run this on windows

### ISSUE THREAD

**Issue by joaochris** [obv-mikhail/InputBot#28]
How do I run this on windows? I want to configure the click on a player within a program. I don't know anything about programming.

**Comment by bburdette** [comment]
@joaochris this is a library you'd use to write a program, its not a program that you run on its own.  Here's a project that uses inputbot to issue mouse clicks and key presses:  https://github.com/bburdette/mousepage

To install rust programs, you'll need [cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html).  Then do `cargo install <programname>`.
