### ISSUE TITLE
[Question] How I capture keyboard inputs globally ?

### ISSUE THREAD

**Issue by andrew-ares** [obv-mikhail/InputBot#34]
I guess this crate is used for automated input, but can I use it to capture global input? Thanks!

**Comment by obv-mikhail** [comment]
You can create global hotkeys like in the README example. If you want to capture all input, and handle it yourself we would need to introduce a new API.

**Comment by andrew-ares** [comment]
It would be great to have such an API. I guess a possible application scenario is to respond to certain events asynchronously.
