### ISSUE TITLE
Latest Crates.io package doesn't include bind_all functionality.

### ISSUE THREAD

**Issue by Mach1212** [obv-mikhail/InputBot#46]

**Comment by positiveway** [comment]
neither 0.5.0 nor 0.5.1 includes it. makes it very confusing when running the example from readme

**Comment by positiveway** [comment]
Got it. Bind_all was added just recently and not included in 0.5.1 version released 3 months ago. So what you need to do is use master branch as a dependency. In Cargo.toml `inputbot = { git = "https://github.com/obv-mikhail/InputBot" }`

**Comment by Mach1212** [comment]
Thank you!
