### ISSUE TITLE
bind_all from examples doesn't exist in 0.5.1

### ISSUE THREAD

**Issue by rm-rf-etc** [obv-mikhail/InputBot#49]
Just a polite request, could you limit the readme examples to things that are in your latest release? `bind_all` is not in 0.5.1, so the basic examples didn't 'just work' and some troubleshooting was required to discover why.

**Comment by jameshulse** [comment]
It works if you install from git instead:
```
[dependencies]
inputbot = { git = "https://github.com/obv-mikhail/InputBot", branch = "develop" }
```

**Comment by obv-mikhail** [comment]
Readme now mentions that git should be used for latest features.
