### ISSUE TITLE
inputbot::KeybdKey::bind_all doesn't work -> there is no bind_all

### ISSUE THREAD

**Issue by NiiightmareXD** [obv-mikhail/InputBot#54]
no variant or associated item named `bind_all` found for enum `KeybdKey` in the current scope
variant or associated item not found in `KeybdKey` rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)

**Comment by jameshulse** [comment]
I had the same issue installing from crates.io. I fixed it by installing from Git instead. In your `Cargo.toml`:

```
[dependencies]
inputbot = { git = "https://github.com/obv-mikhail/InputBot", branch = "develop" }
```
