### ISSUE TITLE
Publish latest crate version

### ISSUE THREAD

**Issue by rigwild** [obv-mikhail/InputBot#77]
Hey, the crate has not been published for more than a year, I am stuck because to publish another crate, you have to use dependencies from crates.io (git dependencies are removed)

Especially since new keys were added in https://github.com/obv-mikhail/InputBot/commit/c391001768704b9e930a22741d5b4e821520848d

Can you please do a publish? Thanks a lot!

**Comment by Redhawk18** [comment]
Id love for this, the last release was in 2020.

**Comment by obv-mikhail** [comment]
Sorry for not publishing earlier. New release published with many changes - https://github.com/obv-mikhail/InputBot/blob/develop/CHANGELOG.md. Thanks to everyone who contributed!

**Comment by rigwild** [comment]
Thanks!
