### ISSUE TITLE
graceful way to end `inputbot::handle_input_events`

### ISSUE THREAD

**Issue by Redhawk18** [obv-mikhail/InputBot#80]
Hi I'm building a gui around this crate, and I enjoy using it. Currently I start `handle_input_events` in a new thread so my gui doesn't freeze, and there's no correct way to end this loop. I could kill the thread but that seems wrong. I'd be open to submitting a pr if i could get some information on what is needed since every platform has a different impl of `handle_input_events`.

**Comment by obv-mikhail** [comment]
Feel free to implement a solution just for the platform you are working on. Maybe a new function called `stop_handling_input_events` could be made?

**Comment by Redhawk18** [comment]
is there a preferred way to stop the loop? the only thing i can think of is a global variable and adding 
```rs
pub fn handle_input_events() {
  if stop { return }
...
}

pub fn stop_handling_input_events() {
  stop = true
  }
```

**Comment by obv-mikhail** [comment]
Sure, something of that nature seems fine.
