### ISSUE TITLE
Method to stop listening to inputs

### ISSUE THREAD

**Issue by sassou5018** [obv-mikhail/InputBot#86]
Is there any method to stop listening to inputs without exiting the process ?

**Comment by jngls** [comment]
If you mean on windows, I also noticed this problem.

I've just submitted https://github.com/obv-mikhail/InputBot/pull/90 to address this. If this PR is accepted you'll be able to stop the blocking call by unbinding all your key/mouse binds.

**Comment by obv-mikhail** [comment]
@alexmadeathing merged your pr, thanks.
